### ISSUE TITLE
OPV +- reversed

### ISSUE THREAD

**Issue by Gerssi** [crycode-de/mpcnc-mega-2560-pro-shield#1]
Hallo, 
im PWM/Analog 0-5V (0-10V) Teil ist meines Erachtens ein Fehler, Pin2 (-) und Pin 3 (+) IC5A sind vertauscht. Ansonsten super Arbeit. Danke.

**Comment by crycode-de** [comment]
Stimmt, die beiden sind vertauscht. Ist uns bislang nie aufgefallen, da wir den Teil der Schaltung noch nicht genutzt haben.

Danke fürs Melden des Problems!

**Comment by crycode-de** [comment]
Problem behoben in _v1.2 Rev. 4_. 🙂

Auf bereits gefertigten PCBs sollte sich das durch auftrennen der beiden Leiterbahnen und zwei kleine Drahtbrücken lösen lassen.

Siehe auch [CHANGELOG.md](https://github.com/crycode-de/mpcnc-mega-2560-pro-shield/blob/master/CHANGELOG.md) bzgl. der Änderung.

@Gerssi Danke noch mal fürs Melden!
